const char* err_msg[] = {
    /*  0 */ "",
    /*  1 */ "Found ':=' when expecting '='.",
    /*  2 */ "There must be a number to follow '='.",
    /*  3 */ "There must be an '=' to follow the identifier.",
    /*  4 */ "There must be an identifier to follow 'const', 'var', 'float' or 'procedure'.",
    /*  5 */ "Missing ';'.",
    /*  6 */ "",
    /*  7 */ "There must be a declaration",
    /*  8 */ "The declaration is followed by an incorrect symbol.",
    /*  9 */ "'.' expected.",
    /* 10 */ "';' expected.",
    /* 11 */ "Undeclared identifier.",
    /* 12 */ "Illegal assignment.",
    /* 13 */ "':=' expected.",
    /* 14 */ "There must be an identifier to follow the 'call'.",
    /* 15 */ "There must be a procedure to follow the 'call'..",
    /* 16 */ "'then' expected.",
    /* 17 */ "';' or 'end' expected.",
    /* 18 */ "'do' expected.",
    /* 19 */ "",
    /* 20 */ "Relative operators expected.",
    /* 21 */ "Procedure identifier can not be in a factor.",
    /* 22 */ "Missing ')'.",
    /* 23 */ "The symbol can not be followed by a factor.",
    /* 24 */ "The symbol can not be as the beginning of an expression.",
    /* 25 */ "Illegal array declaration",
    /* 26 */ "The identifier is too long",
    /* 27 */ "'=' expected.",
    /* 28 */ "Missing ',' or ';'.",
    /* 29 */ "",
    /* 30 */ "The number is too great.",
    /* 31 */ "The number is out of address border",
    /* 32 */ "There are too many levels.",
    /* 33 */ "')' expected.",
    /* 34 */ "'(' expected.",
    /* 35 */ "Read format is expected.",
    /* 36 */ "Illegal format.",
    /* 37 */ "Format and the kind of identifier don't match."
    /* 38 */ "The index is out of range."
    /* 39 */ "']' expected."
    /* 40 */ "Illegal array element to be assigned."
    /* 41 */ "Illegal read."
};